name: qeraat_moshaf_kwait
description: تطبيق مصحف القراءات العشر يمكنك من قراءة القرءان الكريم ومعرفة
  الكلمات الخلافية وطريقة نطقها في القراءات المختلفة .

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 3.0.37+63


environment:
  # sdk: ">=2.17.0 <3.0.0"
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  animate_do: ^3.0.2
  animations: ^2.0.11
  audio_service: ^0.18.9
  audioplayers: ^6.0.0
  convex_bottom_bar:
    path: ./convex_bottom_bar-3.1.0+1/
  csv: ^6.0.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  device_preview: ^1.2.0
  dio: ^5.1.1
  equatable: ^2.0.3
  floating_dialog: ^1.1.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_colorpicker: ^1.1.0
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.7
  flutter_pdfview: ^1.4.0
  flutter_play_asset_delivery:
    git: https://github.com/ahadsiddiquii/flutter_play_asset_delivery.git
  flutter_slidable: ^3.1.0
  flutter_sound: ^9.6.0
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.17
  fluttertoast: 8.0.9
  get_it: ^7.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  intl: any
  just_audio: ^0.9.31
  just_audio_background: ^0.0.1-beta.9
  open_file: ^3.5.10
  path_provider: ^2.0.11
  permission_handler: ^11.4.0
  pinch_zoom_release_unzoom:
    git:
      url: https://github.com/ahadsiddiquii/pinch_zoom_release_unzoom.git
      ref: update/reset-animation-overlay
  pull_to_refresh_flutter3: ^2.0.2
  record: ^5.1.2
  responsive_framework: ^1.5.1
  screenshot: ^3.0.0
  scrollable_positioned_list: ^0.3.8
  share: ^2.0.4
  shared_preferences: ^2.0.15
  sqflite: ^2.3.3+1
  syncfusion_flutter_sliders: ^27.1.56
  translator: ^1.0.3+1
  wakelock_plus: ^1.2.10
  wheel_slider: ^1.0.0
  win32: ^5.10.0
  zoom_widget: ^2.0.1

dev_dependencies:
  build_runner: ^2.2.1
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
flutter_native_splash:
  ios: true
  web: false
  # image: assets/imgs/splash.png
  # image_dark: assets/imgs/splash.png
  # background_image: assets/imgs/splash.png #only required
  landscape: false
  # background_image_dark: assets/imgs/splash.png
  android: true
  android_gravity: fill
  # branding: assets/imgs//pngs/splash.png
  #flutter pub run flutter_native_splash:create
  #flutter pub run flutter_native_splash:remove
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/imgs/app-icon.png"
  image_path_ios: "assets/imgs/app-icon.png"
  remove_alpha_ios: true
  # flutter pub run flutter_launcher_icons:main

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/imgs/
    - assets/icons/
    - assets/suras_names/
    - assets/ahzab_names/
    - assets/ajzaa_names/
    - assets/allah_names/
    - assets/fonts/
    - assets/ayah_svg/
    - assets/database/
    - assets/database/words_rects.csv
    #- assets/database/shamel.db
    # - assets/database/qsa4.db
    - assets/drawer_icons/
    - assets/moshaf_information_pages/
    - assets/hisb_icons/
    - assets/border_hisb/
    - assets/surah_frames/
    - assets/readings_fonts/
    - assets/reciters_photos/
    # - assets/ten_readings/readings_json/
    # - assets/ten_readings/sounds/

  fonts:
    - family: Uthmany
      fonts:
        - asset: assets/fonts/uthmany-regular.ttf
          weight: 500
        - asset: assets/fonts/uthmany-bold.ttf
          weight: 700

    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo-bold.ttf
          weight: 700
        - asset: assets/fonts/cairo-semibold.ttf
          weight: 600
        - asset: assets/fonts/cairo-regular.ttf
          weight: 400
        - asset: assets/fonts/cairo-light.ttf
          weight: 300

    - family: QuranIconsFont
      fonts:
        - asset: assets/fonts/quran_icons.ttf
    - family: UthmanicHafs_V22
      fonts:
        - asset: assets/fonts/UthmanicHafs_V22.ttf

    - family: UthmanicHafs_V20
      fonts:
        - asset: assets/fonts/UthmanicHafs_V20.ttf
    - family: ScheherazadeNew-Regular
      fonts:
        - asset: assets/fonts/ScheherazadeNew-Regular.ttf
    - family: Urdu_Noto
      fonts:
        - asset: assets/fonts/urdu_noto.ttf
    - family: Urdu_Book
      fonts:
        - asset: assets/fonts/urdu_book.ttf

    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Bold.ttf
          weight: 700
        - asset: assets/fonts/Amiri-Regular.ttf
          weight: 400

    # - family: UthmanicHafs
    #   fonts:
    #     - asset: assets/fonts/UthmanicHafs.ttf
    #################################
    # mannan fonts
    # external QCF fonts
    - family: QCF2035
      fonts:
        - asset: assets/readings_fonts/QCF2035.ttf

    - family: QCF2579
      fonts:
        - asset: assets/readings_fonts/QCF2579.ttf

    - family: QCF2540
      fonts:
        - asset: assets/readings_fonts/QCF2540.ttf

    - family: QCF2351
      fonts:
        - asset: assets/readings_fonts/QCF2351.ttf

    - family: QCF2323
      fonts:
        - asset: assets/readings_fonts/QCF2323.ttf

    - family: QCF2322
      fonts:
        - asset: assets/readings_fonts/QCF2322.ttf

    - family: QCF2247
      fonts:
        - asset: assets/readings_fonts/QCF2247.ttf

    - family: QCF2238
      fonts:
        - asset: assets/readings_fonts/QCF2238.ttf

    - family: QCF2175
      fonts:
        - asset: assets/readings_fonts/QCF2175.ttf

    # extenal fonts
    - family: KFGQPCBAZZIUthmanicScript-Regul
      fonts:
        - asset: assets/readings_fonts/UthmanicBazzi1 Ver07.ttf

    - family: KFGQPCUthmanicScriptHAFS
      fonts:
        - asset: assets/readings_fonts/UthmanicHafs_V20.ttf

    - family: KFGQPC-Uthmanic-Script-HAFS
      fonts:
        - asset: assets/readings_fonts/UthmanicHafs_V20.ttf

    - family: TraditionalArabic-Bold
      fonts:
        - asset: assets/readings_fonts/tradbdo.ttf

    - family: TraditionalArabic
      fonts:
        - asset: assets/readings_fonts/tradbdo.ttf

    - family: AdwaaElsalaf-Bold
      fonts:
        - asset: assets/readings_fonts/AdwaaElsalaf-Bold.ttf

    - family: Adwaa-Elsalaf
      fonts:
        - asset: assets/readings_fonts/Adwaa-Elsalaf-light.ttf

    - family: QadiLinotype
      fonts:
        - asset: assets/readings_fonts/QadiLinotype.ttf

    - family: Lotus-Linotype
      fonts:
        - asset: assets/readings_fonts/QadiLinotype.ttf

    - family: AdobeArabic-Regular
      fonts:
        - asset: assets/readings_fonts/AdobeArabic-Regular.otf

    - family: AdobeArabic-Regular
      fonts:
        - asset: assets/readings_fonts/AdobeArabic-Regular.otf

    - family: Adobe-Arabic
      fonts:
        - asset: assets/readings_fonts/AdobeArabic-Regular.otf

    - family: KFGQPCArabicSymbols01
      fonts:
        - asset: assets/readings_fonts/Symbols1_Ver02.otf

    - family: KFGQPC-QUMBUL-Uthmanic-Script
      fonts:
        - asset: assets/readings_fonts/UthmanicQunbul.ttf

    - family: KFGQPC-Uthman-Taha-Naskh
      fonts:
        - asset: assets/readings_fonts/UthmanTN1B Ver10.otf

    - family: KFGQPCUthmanTahaNaskh-Bold
      fonts:
        - asset: assets/readings_fonts/UthmanTN1B Ver10.otf

    - family: KFGQPCUthmanTahaNaskh
      fonts:
        - asset: assets/readings_fonts/UthmanTN1_Ver06.otf

    - family: MinionPro-Regular
      fonts:
        - asset: assets/readings_fonts/MinionPro-Regular.otf

    - family: Minion-Pro
      fonts:
        - asset: assets/readings_fonts/MinionPro-Regular.otf

    - family: Times-New-Roman
      fonts:
        - asset: assets/readings_fonts/times.ttf

    - family: TimesNewRomanPSMT
      fonts:
        - asset: assets/readings_fonts/times.ttf

    - family: LOTUS2007
      fonts:
        - asset: assets/readings_fonts/LOTUS2007-v6-bahnihi-6.ttf

    - family: Lotus-Light
      fonts:
        - asset: assets/readings_fonts/louts_alsharika_alhaditha.ttf

    - family: louts-shamy-modify-2
      fonts:
        - asset: assets/readings_fonts/louts shamy light- modivy 2.ttf

    - family: louts-shamy-Bold
      fonts:
        - asset: assets/readings_fonts/louts shamy bold-v modify 2.ttf

    - family: louts-shamy
      fonts:
        - asset: assets/readings_fonts/louts shamy light-v.ttf

    - family: lOTUS2007-Bold
      fonts:
        - asset: assets/readings_fonts/LOTUS2007-v6-bahnihi-6.ttf

    - family: kn_quran_1
      fonts:
        - asset: assets/readings_fonts/kn_quran_1-19-3-2023-v2.ttf

    - family: kn_quran_2
      fonts:
        - asset: assets/readings_fonts/kn_quran_2-19-3-2023-v2.ttf

    - family: kn_quran_3
      fonts:
        - asset: assets/readings_fonts/kn_quran_3.ttf

    # AGA Arabesque  --> AGA-Arabesque-2.ttf
    # Traditional Naskh  --> TraditionalNashk.ttf
    # AAAGoldenLotus Stg1_Ver1  --> GoldenLotus-Stg1_Ver1.ttf
    # Times New Roman --> times.ttf
    # MS Mincho --> MSMINCHO.TTF
    # Al-QuranAlKareem  --> Al-QuranAlKareem Regular.ttf
    # AGA Islamic Phrases  --> AGA_Islamic_Phrases.TTF
    # Abjad --> Traditional-Arabic.ttf
    # TraditionalArabic-Bold  --> Traditional Arabic-Bold.ttf
    # Traditional Arabic --> Traditional-Arabic.ttf
    # AAA GoldenLotus --> AAAGoldenLotus.ttf
    # TraditionalNaskh-Bold  --> TraditionalNaskh-Bold.ttf
    # TraditionalNaskh  --> TraditionalNaskh.ttf
    - family: AGA Arabesque
      fonts:
        - asset: assets/mannan_fonts/AGA-Arabesque-2.ttf

    - family: Traditional Naskh

      fonts:
        - asset: assets/mannan_fonts/TraditionalNaskh.ttf

    - family: AAAGoldenLotus Stg1_Ver1
      fonts:
        - asset: assets/mannan_fonts/GoldenLotus-Stg1_Ver1.ttf

    - family: Al-QuranAlKareem
      fonts:
        - asset: assets/mannan_fonts/Al-QuranAlKareem Regular.ttf

    - family: Abjad
      fonts:
        - asset: assets/mannan_fonts/Traditional-Arabic.ttf

    - family: TraditionalArabic-Bold
      fonts:
        - asset: assets/mannan_fonts/TraditionalArabic-Bold.ttf #may need a space between traditional and arabic

    - family: Traditional Arabic
      fonts:
        - asset: assets/mannan_fonts/Traditional-Arabic.ttf

    - family: AAA GoldenLotus
      fonts:
        - asset: assets/mannan_fonts/AAAGoldenLotus.ttf

    - family: TraditionalNaskh-Bold
      fonts:
        - asset: assets/mannan_fonts/TraditionalNaskh-Bold.ttf

    - family: TraditionalNaskh
      fonts:
        - asset: assets/mannan_fonts/TraditionalNaskh.ttf

    - family: AAAGoldenLotus Stg1_Ver1
      fonts:
        - asset: assets/mannan_fonts/GoldenLotus-Stg1_Ver1.ttf

    - family: Al-QuranAlKareem
      fonts:
        - asset: assets/mannan_fonts/Al-QuranAlKareem Regular.ttf

    - family: Abjad
      fonts:
        - asset: assets/mannan_fonts/Traditional-Arabic.ttf

    - family: TraditionalArabic-Bold
      fonts:
        - asset: assets/mannan_fonts/TraditionalArabic-Bold.ttf #may need a space between traditional and arabic

    - family: Traditional Arabic
      fonts:
        - asset: assets/mannan_fonts/Traditional-Arabic.ttf

    - family: AAA GoldenLotus
      fonts:
        - asset: assets/mannan_fonts/AAAGoldenLotus.ttf

    - family: TraditionalNaskh-Bold
      fonts:
        - asset: assets/mannan_fonts/TraditionalNaskh-Bold.ttf

    - family: TraditionalNaskh
      fonts:
        - asset: assets/mannan_fonts/TraditionalNaskh.ttf

    - family: AAAGoldenLotus Stg1_Ver1
      fonts:
        - asset: assets/mannan_fonts/GoldenLotus-Stg1_Ver1.ttf

    - family: Times New Roman
      fonts:
        - asset: assets/readings_fonts/times.ttf

    - family: Al-QuranAlKareem
      fonts:
        - asset: assets/mannan_fonts/Al-QuranAlKareem Regular.ttf

    - family: Abjad
      fonts:
        - asset: assets/mannan_fonts/Traditional-Arabic.ttf

    - family: TraditionalArabic-Bold
      fonts:
        - asset: assets/mannan_fonts/TraditionalArabic-Bold.ttf #may need a space between traditional and arabic

    - family: Traditional Arabic
      fonts:
        - asset: assets/mannan_fonts/Traditional-Arabic.ttf

    - family: AAA GoldenLotus
      fonts:
        - asset: assets/mannan_fonts/AAAGoldenLotus.ttf

    - family: TraditionalNaskh-Bold
      fonts:
        - asset: assets/mannan_fonts/TraditionalNaskh-Bold.ttf

    - family: TraditionalNaskh
      fonts:
        - asset: assets/mannan_fonts/TraditionalNaskh.ttf

    - family: QeeratKuwait
      fonts:
        - asset: assets/fonts/QeeratKuwait.ttf

    - family: NotoNaskhArabic-Regular
      fonts:
        - asset: assets/fonts/NotoNaskhArabic-Regular.ttf
    - family: HafsNastaleeqVer10
      fonts:
        - asset: assets/fonts/HafsNastaleeqVer10.otf
